version: 0.2

phases:
  pre_build:
    commands:
      - node -v
      - npm -v

  install:
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - 'build/**/*'
  base-directory: 'my-gallery'
