version: 0.2

phases:
  pre_build:
    commands:
      - node -v
      - npm -v

  install:
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]; then
          echo "Build failed!"
        else
          echo "Build completed successfully"
        fi

artifacts:
  files:
    - 'build/**/*'
  base-directory: 'my-gallery'
