version: 0.2

phases:
  pre_build:
    commands:
      - node -v
      - npm -v

  install:
    commands:
      - node --max-old-space-size=4096 $(which npm) install

  build:
    commands:
      - node --max-old-space-size=4096 $(which npm) run build

artifacts:
  files:
    - 'build/**/*'
  base-directory: 'my-gallery'
