version: 0.2

phases:
  pre_build:
    commands:
      - node -v
      - npm -v

  install:
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - pwd
      - ls
      - aws iam list-roles
      - aws iam get-role --role-name my-gallery-pipeline-admin
      - aws iam list-attached-role-policies --role-name my-gallery-pipeline-admin
      - aws cloudformation deploy --template-file s3-deployment-template.yml --stack-name MyGalleryS3BucketStack --capabilities CAPABILITY_NAMED_IAM --debug || exit 2
