AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Include
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mygallerypicsbucket2
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  MyS3BucketPolicy: !Transform
    Name: 'AWS::Include'
    Parameters:
      Location: 's3-bucket-policy.json'

Outputs:
  S3BucketName:
    Value: !Ref MyS3Bucket
