name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          pwd
          ls
          npm install

      - name: Build project
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build

  tag:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the working directory
        run: pwd

      - name: Get the latest commit hash
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"
          git config --global user.password "${{ secrets.GH_TOKEN }}"
          git tag -a "build-${{ github.run_number }}-${GITHUB_SHA:0:7}" -m "Build ${{ github.run_number }}" $COMMIT_HASH

      - name: Push tags
        run: |
          git push https://${{ secrets.GH_TOKEN }}@github.com/your-username/your-repository --push origin --tags
      - name: Push tags
        run: |
          repo_owner_name="${{ github.repository_owner }}"
          repo_name="${{ github.repository }}"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.repository }} --push origin --tags




  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build

      - name: Deploy to AWS S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Sync to S3 Bucket
        run: aws s3 sync $GITHUB_WORKSPACE/build/ s3://my-gallery-s3-bucket --delete
