name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: List Contents of Working Directory
        run: ls -R

      - name: List Contents of build Directory
        run: ls -R build/

      - name: Debug Environment Variables
        run: env



  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to AWS S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Sync to S3 Bucket
        run: aws s3 sync build s3://mygallerypicsbucket --delete

      - name: Debug AWS CLI Commands
        run: |
          echo "AWS CLI Command: aws s3 sync ./build s3://mygallerypicsbucket"
