name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build

      - name: Create S3 bucket
        run:  aws s3api create-bucket --bucket mygallerypicsbucket1 --region ap-northeast-1

      - name: Configure S3 bucket for static website hosting
        run:  aws s3 website s3://mygallerypicsbucket1 --index-document index.html --error-document error.html


      - name: Deploy to AWS S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Sync to S3 Bucket
        run: aws s3 sync $GITHUB_WORKSPACE/build/ s3://mygallerypicsbucket1 --delete

